Fundamentals of TF

1.Intro to tensors

2.getting info from tensors

3.manipulating tensors

4.tensors and numpy

5.using @tf.function

In [2]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
#creating tensors with tf.constant()

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
#check the dimensions of tensors
scalar.ndim

0

In [7]:
#create a ventor
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
#check the dimension of our vector
vector.ndim

1

In [9]:
#create a matrix(more than one dimension)
matrix=tf.constant([[10,20,30],
                   [20,30,40]])

In [11]:
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [20, 30, 40]], dtype=int32)>

In [12]:
matrix.ndim

2

In [15]:
#matrix
matrix_2=tf.constant([[10.0,7.0],
                      [3.9,4.7]],dtype=tf.float16)

In [17]:
matrix_2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10. ,  7. ],
       [ 3.9,  4.7]], dtype=float16)>

In [18]:
matrix_3=tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])

In [21]:
matrix_3

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [22]:
matrix_3.ndim

3

In [23]:
#scalar,vector,matrix,tensor



In [24]:
v=tf.Variable(1.)

In [25]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [27]:
changeble_tensor=tf.Variable([10,70])
unchanble_tensor=tf.constant([10,7])
changeble_tensor,unchanble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 70], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [29]:
changeble_tensor[0] = 7

TypeError: ignored

In [30]:
#use .assign
changeble_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 7, 70], dtype=int32)>

In [31]:
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 70], dtype=int32)>

In [32]:
unchanble_tensor[0].assign[7]

AttributeError: ignored

In [37]:
# Creating random tensors with TensorFlow

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(2,3))

In [39]:
random_2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [52]:
values=tf.constant([[1,2,3],
                    [4,5,6],
                    [10,34,54]])
x=tf.random.shuffle(values)

In [53]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [10, 34, 54],
       [ 4,  5,  6]], dtype=int32)>

In [58]:
#tf.ones
#tf.zeros
import numpy as np
numpy_A=np.arange(1,30,dtype=np.int32)


In [59]:
A=tf.constant(numpy_A)
B=tf.constant(numpy_A,shape=())

TypeError: ignored

In [60]:
A

<tf.Tensor: shape=(29,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)>

SyntaxError: ignored

### Getting information from tensors

*shape

*rank

*axis

*size



In [67]:
rank_4_tensor=tf.zeros(shape=[4,3,5])

In [68]:
rank_4_tensor

<tf.Tensor: shape=(4, 3, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [70]:
rank_4_tensor.shape


TensorShape([4, 3, 5])

In [72]:
rank_4_tensor.ndim

3

In [74]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=60>