
*Intro to tensors

*getteing information from  tensors

*manipulating tensors

*using @tf.function

*using GPU

*Introduction to tensors

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.7.0


In [ ]:
scalar=tf.constant(7)

In [ ]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector=tf.constant([10,20])

In [ ]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[10,7],
                   [20,30]])

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [20, 30]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix=tf.constant([[10,1],
                            [20,30],
                            [56,78]])

In [ ]:
another_matrix.ndim

2

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  1],
       [20, 30],
       [56, 78]], dtype=int32)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                    [[1,2,3],
                     [1,2,3]],
                    [[1,2,3],[1,2,3]]])

In [ ]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [ ]:
tensor.ndim

3

tf.variable

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
c=tf.Variable([10,7])
u=tf.constant([10,2])

In [ ]:
c

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
u

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

In [ ]:
tf.random.Generator.from_seed(42)

In [ ]:
#Random tensors

In [ ]:
random_1=tf.random.normal(shape=(3,2))

In [ ]:
random_2=tf.random.normal(shape=(3,2))

In [ ]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.58557034, -0.8587513 ],
       [-0.51721835,  0.69914013],
       [-0.35561776,  0.25735372]], dtype=float32)>

In [ ]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.02481285, -0.29473644],
       [-0.00277905, -0.01533754],
       [-1.7313026 , -0.04108538]], dtype=float32)>

* Shuffle the order of the tensor

In [ ]:
not_shuffled=tf.constant([
                          [1,2,3],
                          [4,5,6],
                          [7,8,9]
])

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
A=tf.constant()

In [ ]:
rank_4=tf.zeros(shape=[2,3,4,5])

In [ ]:
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4.ndim

4

In [ ]:
some_list=[1,2,3,4]

In [ ]:
some_list[:2]

[1, 2]

In [ ]:
rank_4[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get the first elemnt

In [ ]:
some_list[:1]

[1]

In [ ]:
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [ ]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.26226163, 0.8790015 , 0.8160318 , 0.20900679, 0.4569031 ,
           0.25489616, 0.87143135, 0.5380603 , 0.737414  , 0.8573533 ,
           0.28227603, 0.54132235, 0.36323774, 0.83197045, 0.8566108 ,
           0.98120046, 0.7295182 , 0.02893472, 0.26932836, 0.39960563,
           0.5840845 , 0.06204879, 0.13952422, 0.5643445 , 0.19557023,
           0.7320336 , 0.7770957 , 0.25619853, 0.42047536, 0.627329  ,
           0.22665608, 0.08444285, 0.44425273, 0.32592988, 0.7817607 ,
           0.40259373, 0.09081244, 0.3637644 , 0.9195895 , 0.65487874,
           0.6526811 , 0.6856688 , 0.8740263 , 0.8619127 , 0.49802732,
           0.13141668, 0.8901793 , 0.32607174, 0.74153626, 0.34969556]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeeze=tf.squeeze(G)

In [ ]:
G_squeeze

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.26226163, 0.8790015 , 0.8160318 , 0.20900679, 0.4569031 ,
       0.25489616, 0.87143135, 0.5380603 , 0.737414  , 0.8573533 ,
       0.28227603, 0.54132235, 0.36323774, 0.83197045, 0.8566108 ,
       0.98120046, 0.7295182 , 0.02893472, 0.26932836, 0.39960563,
       0.5840845 , 0.06204879, 0.13952422, 0.5643445 , 0.19557023,
       0.7320336 , 0.7770957 , 0.25619853, 0.42047536, 0.627329  ,
       0.22665608, 0.08444285, 0.44425273, 0.32592988, 0.7817607 ,
       0.40259373, 0.09081244, 0.3637644 , 0.9195895 , 0.65487874,
       0.6526811 , 0.6856688 , 0.8740263 , 0.8619127 , 0.49802732,
       0.13141668, 0.8901793 , 0.32607174, 0.74153626, 0.34969556],
      dtype=float32)>

In [ ]:
G_squeeze.shape

TensorShape([50])